"""создание таблиц

Revision ID: 84b1b6995ef5
Revises: 
Create Date: 2026-05-07 12:54:18.579948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84b1b6995ef5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sales_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('total_margin', sa.Float(), nullable=False),
    sa.Column('total_margin_percent', sa.Float(), nullable=False),
    sa.Column('top_dishes_json', sa.Text(), nullable=True),
    sa.Column('loss_making_dishes_json', sa.Text(), nullable=True),
    sa.Column('suggestions_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_sales_summary_sale_date'), 'daily_sales_summary', ['sale_date'], unique=True)
    op.create_table('dish_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dish_name', sa.String(length=255), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('margin_percent', sa.Float(), nullable=True),
    sa.Column('total_revenue_per_dish', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_sales_dish_name'), 'dish_sales', ['dish_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dish_sales_dish_name'), table_name='dish_sales')
    op.drop_table('dish_sales')
    op.drop_index(op.f('ix_daily_sales_summary_sale_date'), table_name='daily_sales_summary')
    op.drop_table('daily_sales_summary')
    # ### end Alembic commands ###
